config/routes.rb
Rails.application.routes.draw do
  devise_for :users,
  controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }
  root to: 'pages#home'
  resources :cryptos
  get '/pages/advices', to: 'pages#advices'
  get '/pages/sources', to: 'pages#sources'
  get '/pages/donation', to: 'pages#donation'
  get '/pages/history', to: 'pages#history'
  get '/pages/prices', to: 'pages#prices'
  get '/pages/converter', to: 'pages#converter'
  get '/pages/tutorial', to: 'pages#tutorial'
  get '/pages/wallet', to: 'pages#wallet'
  get '/pages/lexique', to: 'pages#lexique'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/crypto.rb
class Crypto < ApplicationRecord
 mount_uploader :photo, PhotoUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,:omniauthable, omniauth_providers: [:facebook]


  def self.find_for_facebook_oauth(auth)
    user_params = auth.slice(:provider, :uid)
    user_params.merge! auth.info.slice(:email, :first_name, :last_name)
    user_params[:facebook_picture_url] = auth.info.image
    user_params[:token] = auth.credentials.token
    user_params[:token_expiry] = Time.at(auth.credentials.expires_at)
    user_params = user_params.to_h

    user = User.find_by(provider: auth.provider, uid: auth.uid)
    user ||= User.find_by(email: auth.info.email) # User did a regular sign up in the past.
    if user
      user.update(user_params)
    else
      user = User.new(user_params)
      user.password = Devise.friendly_token[0,20]  # Fake password for validation
      user.save
    end

    return user
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  config.relative_url_root = ""
end

app/controllers/cryptos_controller.rb
class CryptosController < ApplicationController
  before_action :set_crypto, only: [:show, :edit, :update, :destroy]
  before_action :all_crypto, only: [:index, :categories, :address, :rating, :price]
  def index
  end
  def categories
  end
  def address
  end
  def rating
  end
  def price
  end
  def show
  end
  def new
    @crypto = Crypto.new
  end
  def create
    crypto = Crypto.create(crypto_params)
        redirect_to crypto_path(crypto)
  end
  def edit
  end
  def update
    @crypto.update(crypto_params)
      redirect_to cryptos_path
  end
  def destroy
    @crypto.destroy
    redirect_to cryptos_path
  end
  private
  def crypto_params
    params.require(:crypto).permit(:name,:description, :address, :date, :photo, :photo_cache, :notice, :website)
  end
  def set_crypto
    @crypto = Crypto.find(params[:id])
  end
  def all_crypto
    @cryptos = Crypto.all
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: [:home, :donation, :prices, :sources, :converter, :tutorial]

  def home
  end

  def donation
  end

  def prices
  end

  def sources
  end

  def converter
  end

  def tutorial
  end

  def advices
  end

  def lexique
  end

end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  def facebook
    user = User.find_for_facebook_oauth(request.env['omniauth.auth'])

    if user.persisted?
      sign_in_and_redirect user, event: :authentication
      set_flash_message(:notice, :success, kind: 'Facebook') if is_navigational_format?
    else
      session['devise.facebook_data'] = request.env['omniauth.auth']
      redirect_to new_user_registration_url
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/cryptos/_forms.html.erb
<div class="wrapper-grey padded">

  <%= simple_form_for(@crypto) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :name, placeholder: "Le nom de la crypto" %>
    <%= f.input :address, placeholder: "Description en quelques mots" %>
    <%= f.input :description, placeholder: "Descriptions complète" %>
    <%= f.input :notice, placeholder: "Remarque personelle" %>
    <%= f.input :website, placeholder: "Website" %>
    <%= f.input :date, placeholder: "Les dates à venir" %>
    <%= f.input :photo %>
    <%= f.input :photo_cache, as: :hidden %>
  </div>
  <br>

  <div class="form-actions">

  </div>
  <br>
  <div class="form-actions">
    <%= f.button :submit %>
  </div>

  <% end %>


</div>

app/views/cryptos/edit.html.erb
<div class="wrapper-grey padded">
  <div class="container">
    <div class="row">
      <div class="col-sm-4 col-sm-offset-4 col-xs-4 col-xs-offset-3 ">
          <br><br><br>
        <h1>Editing <%= @crypto.name %></h1>

        <%= render 'forms', crypto: @crypto %>

        <%= link_to 'Show', @crypto %> |
        <%= link_to 'Back', crypto_path %>
      </div>
    </div>
  </div>

</div>

app/views/cryptos/index.html.erb
<%
require 'net/http'
require 'json'
%>
<br><br><br><br>

<h2 class="text-center searchby1">Les cryptos <br><br><br></h2>
<% sorted = @cryptos.sort_by { |k| k["name"] } %>
<% sorted.each do |crypto| %>
<%
url = 'https://api.coinmarketcap.com/v1/ticker/'+ crypto.name+'/'
uri = URI(url)
response = Net::HTTP.get(uri)
JSON.parse(response)

@my_hash = JSON.parse(response)
%>
<%= link_to crypto_path(crypto), :style => "color:black;" do %>
<div class="wrapper-grey padded">
  <div class="container1">
    <div class="row1">
      <div class="col-xs-12 col-sm-4 col-md-3">
        <div class="card1" style="margin-top: 10px;background-color:white;">

          <div class="first-line" style="display: flex;justify-content:space-between;" >
            <% if @my_hash.first.count == 2 %>
            <div class="card1-description" style=" margin-left: 10px;">
              <h4><%=crypto.name%></h4>
              <span style=" font-size: 14px;">Not found $</span>
              <p style="font-size: 11px;"><%= crypto.address%></p>
              <p style="font-size: 11px;">Change the name please.</p>

            </div>
            <% else %>

            <div class="card1-description" style=" margin-left: 10px;">
              <h4><%=crypto.name%></h4>



              <span style=" font-size: 14px;"><%= @my_hash[0]["price_usd"] %> $</span>



              <p style="font-size: 11px;"><%= crypto.address%></p>
              <p style="font-size: 11px;">1H:
                <% if @my_hash[0]["percent_change_1h"][0] == "-"%>
                <span style="color: red;">
                  <%= @my_hash[0]["percent_change_1h"] %>%
                </span>
                <% else%>
                <span style="color: green;">
                  <%= @my_hash[0]["percent_change_1h"] %>%
                </span>
                <%end %>
                24h:
                <% if @my_hash[0]["percent_change_24h"][0] == "-"%>
                <span style="color: red;">
                  <%= @my_hash[0]["percent_change_24h"] %>%
                </span>
                <% else%>
                <span style="color: green;">
                  <%= @my_hash[0]["percent_change_24h"] %>%
                </span>
                <%end %>
                7days:
                <% if @my_hash[0]["percent_change_7d"][0] == "-"%>
                <span style="color: red;">
                  <%= @my_hash[0]["percent_change_7d"] %>%
                </span>
                <% else%>
                <span style="color: green;">
                  <%= @my_hash[0]["percent_change_7d"] %>%
                </span>
                <%end %>
              </p>
            </div>

            <div style="margin-top: 10px; margin-right: 10px;">
              <%= cl_image_tag crypto.photo, height: 50, width: 50, crop: :scale %>
            </div>

            <% end %>
          </div>
        </div>
      </div>
      <% end %>
    </div>
  </div>
</div>
<% end %>




<div class="wrapper-grey padded">
  <div class="container1">
    <div class="row1">
      <div class="col-xs-12 col-sm-4 col-md-3">
        <div class="card1" style="margin-top: 10px;background-color:white;">
          <div class="first-line" style="display: flex;justify-content:space-between;" >
            <div class="card1-description" style=" margin-left: 10px;">
              <h4><br></h4>
              <span style=" font-size: 14px;"><%= link_to "Add a new crypto", new_crypto_path %> <br> <br></span>
              <p style="font-size: 11px;"><br></p>
              <p style="font-size: 11px;">

              </p>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>


<br> <br> <br><br> <br> <br><br> <br> <br> <br> <br> <br><br> <br>

<br> <br> <br><br> <br> <br><br> <br> <br> <br> <br> <br><br> <br>
<style>
.card1 {
  box-shadow: 0 1px 2px rgba(0,0,0,0.15);
  transition: box-shadow 0.3s ease-in-out;
}
.card1:hover {
  box-shadow: 0 5px 15px rgba(0,0,0,0.3);
}
.card1:hover::after {
  opacity: 1;
}

</style>

app/views/cryptos/new.html.erb
<div class="wrapper-grey padded">
  <div class="container">
    <div class="row">
      <div class="col-sm-4 col-sm-offset-4 col-xs-4 col-xs-offset-3 ">
        <br><br><br>
        <h1>New crypto</h1>
        <%= render 'forms', crypto: @crypto %>
        <%= link_to 'Back', cryptos_path %>
      </div>
    </div>
  </div>
</div>

app/views/cryptos/show.html.erb
<%
require 'net/http'
require 'json'

url = 'https://api.coinmarketcap.com/v1/ticker/'+ @crypto.name+'/'
uri = URI(url)
response = Net::HTTP.get(uri)
JSON.parse(response)

@my_hash = JSON.parse(response)
%>


<br><br><br><br>

<h3 class="text-center" ><%= @crypto.name %> </h3>
<div style="margin-left: 10%; margin-right: 10%;">
  <br>
  <br>

  <% if response == "{\n    \"error\": \"id not found\"\n}" %>
  Le nom de la crypto est incorrecte, il doit être similaire que celui sur <a href="https://coinmarketcap.com/">Coinmarketcap</a>. <br>
  <%= link_to "Modifie", edit_crypto_path %> le nom, si il y a un espace remplace le par un "-". Exemple pour Bitcoin cash => bitcoin-cash. Merci <br><br>
  <% else %>

  <div class="first-line" style="display: flex;justify-content:space-between; background-color:white; padding: 20px 20px 10px 20px; " >


    <div class="first-one" >



      <%= @my_hash[0]["symbol"] %>
      Percent change; <br><br> 1H:
      <% if @my_hash[0]["percent_change_1h"][0] == "-"%>
      <span style="color: red;">
        <%= @my_hash[0]["percent_change_1h"] %>%
      </span> <br>
      <% else%>
      <span style="color: green;">
        <%= @my_hash[0]["percent_change_1h"] %>%
      </span> <br>
      <%end %>
      24h:
      <% if @my_hash[0]["percent_change_24h"][0] == "-"%>
      <span style="color: red;">
        <%= @my_hash[0]["percent_change_24h"] %>%
      </span> <br>
      <% else%>
      <span style="color: green;">
        <%= @my_hash[0]["percent_change_24h"] %>%
      </span> <br>
      <%end %>
      7days:
      <% if @my_hash[0]["percent_change_7d"][0] == "-"%>
      <span style="color: red;">
        <%= @my_hash[0]["percent_change_7d"] %>%
      </span> <br>
      <% else%>
      <span style="color: green;">
        <%= @my_hash[0]["percent_change_7d"] %>%
      </span> <br>
      <%end %>
    </div>

    <div class="first-one-one-one"  >

      <span style="">
        <%= @crypto.name %> price;
        <br><br>
        BTC <%= @my_hash[0]["price_btc"] %>
        <br>
        $  <%= @my_hash[0]["price_usd"] %>
        <br>
      </span>
    </div>



    <div class="second" >
      <%= cl_image_tag @crypto.photo, height: 150, width: 150, crop: :scale %>
    </div>



  </div>




  <br><br>

  <h4 > Description </h4>
  <div style="white-space: pre-line;"><%= @crypto.description %></div>
  <br><br>
  <h4 > Remarque </h4>
  <div style="white-space: pre-line;"><%= @crypto.notice %></div>
  <br><br>
  <h4 > Website </h4>
  <a href="<%= @crypto.website %>" target=_blank>
    <div style="white-space: pre-line;"><%= @crypto.website %></div>
  </a>
  <br><br>
  <h4 > Dates </h4>
  <div style="white-space: pre-line;"><%= @crypto.date %></div>
  <br><br>
  <%= link_to "Edit", edit_crypto_path %> |
  <%= link_to "Back", cryptos_path %>


  <% end %>
  <br>
  <%= link_to "Edit", edit_crypto_path %> |
  <%= link_to "Back", cryptos_path %>
</div>

<style>
@media only screen and (max-width: 600px) {

  .second{
    display: none;
  }
}
.first-line {
  box-shadow: 0 1px 2px rgba(0,0,0,0.15);
  transition: box-shadow 0.3s ease-in-out;
}

</style>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <%= favicon_link_tag 'favicon.ico' %>
  <title>BitGoCoin</title>
  <%= csrf_meta_tags %>
  <%= action_cable_meta_tag %>
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%=stylesheet_link_tag 'application', 'https://fonts.googleapis.com/css?family=Roboto" rel="stylesheet'%>
</head>
<body>
  <%= render 'shared/navbar' %>
  <%= render 'shared/flashes' %>
  <%= yield %>
  <%= javascript_include_tag 'application' %>
  <style>
  h1 {
    font-family: 'Roboto', sans-serif;
  }
</style>
</body>
</html>

app/views/pages/advices.html.erb
wiki

app/views/pages/converter.html.erb
  <%
  require 'net/http'
  require 'json'

  url = 'https://api.coinmarketcap.com/v1/ticker/bitcoin/'
  uri = URI(url)
  response = Net::HTTP.get(uri)
  JSON.parse(response)

  @my_hash = JSON.parse(response)
  price_usd = @my_hash[0]["price_usd"]
  %>


  <div class="converter_place text-center">
    <div class="container1.13">
      <h1>BTC to USD</h1>
      <div class="basefont"><p style="margin-left: 60px;">Price:</p><input type="text" style="width: 100px; margin-left: 30px;" class="chosen" value="<%=price_usd%>" placeholder="<%=price_usd%>">USD</div>
      <div class="px-em">
        <div class="px"><input type="text" class ="input px-input" placeholder="0"/><div class="text">usd</div></div>
        <div class="em"><input type="text" class ="input em-input" placeholder="0"/><div class="text">btc</div></div>
      </div>

    </div>
  </div>


  <style>
  .converter_place {
    height: 50%;
    margin: 0 auto;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding-top: 5em;
    font-family: 'Raleway';
  }
  .container {
    height: 50%;
    margin: 0 auto;
    display: flex;
    flex-direction: column;
    align-items: center;
    justify-content: center;
    padding-top: 5em;
    font-family: 'Raleway';

    h1 {
      font-size: 5.85rem;
      padding: 0 0 .2em 0;
      margin: 0;
    }
  }

  .input {
    border-top: none;
    border-left: none;
    border-right: none;
    padding-top: .4em;
    border-bottom: 1px dotted #000;
    outline: none;
    width: 150px;
    font-size: 3rem;
    text-align: right;
    margin-right: .3em;
    background-color: #f4f4f4;
    outline: none;

    &::-webkit-input-placeholder {
      color: #000;
      opacity: .2;
    }
  }

  .px-em {
    display: flex;
  }

  .px, .em {
    font-size: 2.5rem;
    display: flex;
    justify-content: flex-end;
    align-items: flex-end;

    .text {
      padding-bottom: .2em;
    }
  }

  .em {
    margin-left: 1em;

    .text {
      margin-right: -.3em;
    }
  }

  .px-input {
    width: 105px;
  }
  .em-input {
    width: 160px;
  }

  .basefont {
    display: flex;
    align-items: baseline;
    font-family: 'Raleway';
    font-size: 2.3rem;
    padding: 0 0 0em 0;
    margin: 0;
    border-bottom: 1px solid transparent;
    width: 195px;
    p {
      margin: 0;
      padding: 0;
    }

    .chosen {
      width: 80px;
      border-top: none;
      border-right: none;
      border-left: none;
      margin-left: .2em;
      margin-right: .2em;
      font-size: 3.3rem;
      text-align: center;
      border-bottom: 2px dotted #000;
      background-color: #FF90B3;
      outline: none;

      &::-webkit-input-placeholder {
        color: #000;
        opacity: .2;
      }
    }
  }
</style>

app/views/pages/donation.html.erb
donation in progress

app/views/pages/home.html.erb
<div class="homepage">

<div id="bitcoin">
  <svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" x="0px" y="0px"
  width="200px" height="200px" viewBox="100 100 400 400" xml:space="preserve">
  <filter id="dropshadow" height="130%">
    <feGaussianBlur in="SourceAlpha" stdDeviation="5"/>
    <feOffset dx="0" dy="0" result="offsetblur"/>
    <feFlood flood-color="red"/>
    <feComposite in2="offsetblur" operator="in"/>
    <feMerge>
      <feMergeNode/>
      <feMergeNode in="SourceGraphic"/>
    </feMerge>
  </filter>
  <path class="path" style="filter:url(#dropshadow)" fill="#000000" d="M446.089,261.45c6.135-41.001-25.084-63.033-67.769-77.735l13.844-55.532l-33.801-8.424l-13.48,54.068
  c-8.896-2.217-18.015-4.304-27.091-6.371l13.568-54.429l-33.776-8.424l-13.861,55.521c-7.354-1.676-14.575-3.328-21.587-5.073
  l0.034-0.171l-46.617-11.64l-8.993,36.102c0,0,25.08,5.746,24.549,6.105c13.689,3.42,16.159,12.478,15.75,19.658L208.93,357.23
  c-1.675,4.158-5.925,10.401-15.494,8.031c0.338,0.485-24.579-6.134-24.579-6.134l-9.631,40.468l36.843,9.188
  c8.178,2.051,16.209,4.19,24.098,6.217l-13.978,56.17l33.764,8.424l13.852-55.571c9.235,2.499,18.186,4.813,26.948,6.995
  l-13.802,55.309l33.801,8.424l13.994-56.061c57.648,10.902,100.998,6.502,119.237-45.627c14.705-41.979-0.731-66.193-31.06-81.984
  C425.008,305.984,441.655,291.455,446.089,261.45z M368.859,369.754c-10.455,41.983-81.128,19.285-104.052,13.589l18.562-74.404
  C306.28,314.65,379.774,325.975,368.859,369.754z M379.302,260.846c-9.527,38.187-68.358,18.781-87.442,14.023l16.828-67.489
  C327.767,212.14,389.234,221.02,379.302,260.846z"/>

</svg>
</div>
</div>

<style>
.homepage{

  font-weight: 300;}

  #bitcoin{
    padding-top:80px;
    width:200px;
    margin:0 auto;
    display:block;
    text-align:center;
    color:#888888;}

    .path {
      stroke-dasharray: 2110;
      stroke-dashoffset: 2110;
      stroke-width:2;
      stroke-linecap:round;
      animation: dash 6s linear infinite;
      fill-opacity:0;
      stroke:orange;
    }

    @keyframes dash {
      0% {
        stroke-dashoffset: 2110;
        opacity:0;
        stroke:orange;
      }
      15%{
        opacity:1;
        stroke:orange;
      }
      70%{
        opacity:1;
        stroke:orange;
      }
      100%{
        stroke-dashoffset:0;
        opacity:0;
        stroke:yellow;
      }
    }
  </style>

app/views/pages/lexique.html.erb
<br><br><br><br><br><br>

<p><span style="font-weight: 900;">Altcoins:</span> ce sont toutes les cyptos monnaies qui sont autres que le bitcoin. Exemple: waves, decred, lisk, ... Vous pouvez en acheter avec le bitcoin sur les plateforme de trading comme Bittrex, Kraken, ... (voir sources)</p>

<p><span style="font-weight: 900;">ATH: </span>All Time High, c'est lorsque la valeur de l'action est à son plus haut.</p>

<p><span style="font-weight: 900;">Hold: </span> C'est lorsqu'on décide de "Holder", de garder une action sur du long terme.</p>

<p><span style="font-weight: 900;">Daytrade: </span> C'est lorsqu'on joue sur les cours quotidien, on achète et on revend le jour même.</p>

app/views/pages/prices.html.erb
<% require 'coinbase/wallet'

client = Coinbase::Wallet::Client.new(api_key: 'a39d5d67b37ecf3eedebc166688bdbfb2bd59bef6f53653eb343017db64d4e1b',
  api_secret: '4eb1e71269ce9907dfbfa998b8a3b904483e4cc450ce268a1bd81543cfb5c5ff',
  CB_VERSION: 'YYYY-MM-DD')

    currency_code = 'USD'  # can also use EUR, CAD, etc.

    # Make the request
    price = client.spot_price({currency: currency_code})
    price_usd_btc = price.amount

    %>


    <%  "Current bitcoin price in #{currency_code}: #{price.amount}" %>
    <br><br>

    <%     currency_code = 'EUR'  # can also use EUR, CAD, etc.

    # Make the request
    price = client.spot_price({currency: currency_code})
    price_eur_btc = price.amount

    %>


    <%  "Current bitcoin price in #{currency_code}: #{price.amount}" %>


    <div class="graph">
      <h1>Live Bitcoin Data</h1>
      <div id="placeholder3"></div>

      <div id="placeholder"></div>
      <div class="btcwdgt-chart" bw-theme="light"><script>
        (function(b,i,t,C,O,I,N) {
          window.addEventListener('load',function() {
            if(b.getElementById(C))return;
            I=b.createElement(i),N=b.getElementsByTagName(i)[0];
            I.src=t;I.id=C;N.parentNode.insertBefore(I, N);
          },false)
        })(document,'script','https://widgets.bitcoin.com/widget.js','btcwdgt');
      </script></div>

    </div>


    <br><br><br>

app/views/pages/tutorial.html.erb
<br>
<br>
<div class="text-center">
  <h1>Acheter des Bitcoins</h1>

  <div class="buy-btc" style="display: flex;justify-content:space-between; background-color:white; padding: 20px 20px 10px 20px; ">


    <div class="step-one" style="width: 300px; font-size: 12px;margin-right:10px;">
      <a href="https://www.coinbase.com/join/5999d0aeb93c0a00d93f15f1">
        <img alt="a face that is unnervingly happy" height="67" src="http://icons.iconarchive.com/icons/elegantthemes/beautiful-flat/128/compose-icon.png">
      </a>
      <br><br>
       Inscrivez-vous sur <a href="https://www.coinbase.com/join/5999d0aeb93c0a00d93f15f1" target=_blank>Coinbase</a> <br> <br>
    </div>


    <div class="step-two" style="width: 300px; font-size: 12px;margin-right:10px;">
      <img alt="a face that is unnervingly happy" height="67" src="http://icons.iconarchive.com/icons/elegantthemes/beautiful-flat/128/locked-icon.png">
      <br><br>
       Sécurisez votre compte en ajoutant votre numéro de téléphone <br> <br>
    </div>

    <div class="step-tree" style="width: 300px; font-size: 12px;margin-right:10px;">
      <img alt="a face that is unnervingly happy" height="67" src="http://icons.iconarchive.com/icons/elegantthemes/beautiful-flat/128/creditcard-icon.png">
      <br><br>
       Rajoutez une méthode de payement (paramètres <i class="fa fa-arrow-right" aria-hidden="true"></i> méthode de payment)
      <br><br>
    </div>

    <div class="step-four" style="width: 300px; font-size: 12px;margin-right:10px;">
      <img alt="a face that is unnervingly happy" height="67" src="http://icons.iconarchive.com/icons/elegantthemes/beautiful-flat/128/money-icon.png">
      <br><br>
       Faite un dépot en Euro sur votre compte (onglet compte) <br> Cela peut prendre du temps. <br><br>
    </div>

    <div class="step-five" style="width: 300px; font-size: 12px;margin-right:10px;">
      <img alt="a face that is unnervingly happy" height="67" src="http://icons.iconarchive.com/icons/elegantthemes/beautiful-flat/128/cart-icon.png">
      <br><br>
       Achetez vos bitcoins (onlget Achat/Vente)
      <br>
      <br>
    </div>

  </div>

  <h1>Acheter des Altcoins</h1>
  <br>
  <i class="fa fa-btc" aria-hidden="true"></i> Vous devez avoir des bitcoins sur coinbase.
  <br>

  <br>
  <i class="fa fa-pencil-square-o" aria-hidden="true"></i> Inscrivez-vous sur <a href="https://www.bittrex.com" target=_blank>Bittrex</a> <br><br>

  <i class="fa fa-lock" aria-hidden="true"></i> Sécurisez votre compte en ajoutant votre numéro de téléphone <br> <br>
  <i class="fa fa-address-book-o" aria-hidden="true"></i> Allez dans votre "wallet" et copié votre adresse bitcoin. <br><p style="font-size:12px; font-style: italic;"><br>Pour cela il vous faudra cliquer sur le bouton bleu "+" à gauche de bitcoin et copier l'adresse qui s'affiche,<br> ce sera votre adresse bitcoin pour votre compte bittrex (ex:1Jte1iy3CJuBon9NAtTjgc114EnYPF2cGX).</p> <br>

  <i class="fa fa-rocket" aria-hidden="true"></i>
  Rendez vous sur votre compte coinbase dans l'onglet "comptes", cliquer sur "envoyer" à coté de vos bitcoins, <br>et rentrer l'adresse de votre compte bittrex.
  <br><br>
  <i class="fa fa-btc" aria-hidden="true"></i>
  Vous disposez maintenant de bitcoins sur Bittrex, vous pouvez acheter les altcoins de votre choix.
  <br>
  <br>
  <br>
</div>

app/views/pages/wallet.html.erb
my wallllettt

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <%= alert %>
  </div>
<% end %>